development:
  adapter: postgresql
  encoding: unicode
  database: bhsc_development
  pool: 5
  username: ccandelora
  password: Bytes1010

test:
  adapter: postgresql
  encoding: unicode
  database: bhsc_test
  pool: 5
  username: ccandelora
  password: Bytes1010